language: java
jdk:
  - openjdk8
sudo: false
script: mvn clean package -Dgpg.skip=true
after_success:
  - if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn test cobertura:cobertura coveralls:report; fi
