language: java
jdk:
  - openjdk8
sudo: false
script: mvn clean package -Dgpg.skip=true
after_success:
  - echo "$JAVA_HOME"
  - if [ "$JAVA_HOME" = "/home/travis/openjdk8" ]; then mvn test cobertura:cobertura coveralls:report; fi
